apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-trigger-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-pipeline-run-
    spec:
      pipelineRef:
        name: build-pipeline
      workspaces:
      - name: shared-workspace
        persistentvolumeclaim:
          claimName: fileserver-claim
      - name: shared-ops-workspace
        persistentvolumeclaim:
          claimName: fileserver-claim
      serviceAccountName: build-bot
      podTemplate:
        volumes:
        - name: buildpacks-cache
          persistentVolumeClaim:
            claimName: buildpacks-cache-pvc
      params:
      - name: repo-url
        value: $(params.REPO_URL)
      - name: revision
        value: $(params.REVISION)
      - name: github-token-secret
        value: github-token
      - name: github-token-secret-key
        value: GITHUB_TOKEN
  params:
  - name: REPO_URL
    description: The Git repository url to build and deploy.
  - name: REVISION
    description: The Git revision to build and deploy.
