apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-demo-app-image
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cicd/kpack/image.yaml
    repoURL: https://github.com/springone-tour-2020-cicd/go-demo-app-ops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
