apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-go-demo-app
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ops/overlays/prod
    repoURL: https://github.com/springone-tour-2020-cicd/go-demo-app-ops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
