apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
namespace: dev
images:
  - name: andreasevers/go-demo-app # used for Kustomize matching
    newTag: b3.20200628.232414
namePrefix: dev-
